"""Seed generator for randomly selecting and retrieving images from Pinecone."""

import os
import random
import base64
from pathlib import Path
from typing import Optional, Dict, Any

from ..config.config import Config
from ..pojo.models import ArtCategory
from ..db.vector_dao import VectorDBIngestor
from ..utils.utils import generate_image_id
try:
    from langchain_openai import ChatOpenAI
    from langchain_core.messages import HumanMessage
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False
    print("⚠️  LangChain OpenAI package not installed. Using fallback seed generation.")


class SeedGenerator:
    """Generate random seeds by selecting random images from art categories."""
    
    def __init__(self):
        """Initialize the seed generator with VectorDBIngestor."""
        self.vector_ingestor = None
        self._initialize_vector_ingestor()
    
    def _initialize_vector_ingestor(self):
        """Initialize VectorDBIngestor for Pinecone operations."""
        try:
            self.vector_ingestor = VectorDBIngestor()
            print(f"✅ Connected to Pinecone via VectorDBIngestor")
            
        except Exception as e:
            print(f"❌ Error initializing VectorDBIngestor: {e}")
            self.vector_ingestor = None
    
    def _get_random_category(self) -> ArtCategory:
        """Get a random art category from the enum."""
        return random.choice(list(ArtCategory))
    
    def _get_random_image_path(self, category: ArtCategory) -> Optional[str]:
        """Get a random image path from the specified category in training set."""
        category_path = Path(Config.DATASET_PATH) / "training_set" / category.value
        
        if not category_path.exists():
            print(f"❌ Category path does not exist: {category_path}")
            return None
        
        # Get all image files in the category
        image_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.tiff'}
        image_files = [
            f for f in category_path.iterdir()
            if f.is_file() and f.suffix.lower() in image_extensions
        ]
        
        if not image_files:
            print(f"❌ No image files found in category: {category.value}")
            return None
        
        # Select a random image
        random_image = random.choice(image_files)
        return str(random_image)
    
    def _calculate_image_id(self, image_path: str) -> str:
        """Calculate the image ID using utility function."""
        return generate_image_id(image_path)
    
    def _fetch_from_pinecone(self, image_id: str) -> Optional[Dict[str, Any]]:
        """Fetch the image entry from Pinecone by ID using VectorDBIngestor."""
        if not self.vector_ingestor:
            print("❌ VectorDBIngestor not available")
            return None
        
        return self.vector_ingestor.fetch_by_id(image_id)
    
    def _generate_gpt4o_seed(self, image_path: str, description: str, art_category: str) -> Optional[str]:
        """Generate a short seed description using GPT-4o via LangChain with image input.
        
        Args:
            image_path: Path to the original image
            description: Original image description
            art_category: Art category (drawing, painting, etc.)
            
        Returns:
            Short seed description (8-10 words) generated by GPT-4o
        """
        if not OPENAI_AVAILABLE:
            print("❌ LangChain OpenAI not available")
            return None
        
        try:
            # Check for API key
            if not Config.OPENAI_API_KEY:
                print("❌ OPENAI_API_KEY not found in environment variables")
                return None
            
            # Check if image file exists
            if not Path(image_path).exists():
                print(f"❌ Image file not found: {image_path}")
                return None
            
            # Read and encode image as base64
            try:
                with open(image_path, "rb") as image_file:
                    image_data = image_file.read()
                    base64_image = base64.b64encode(image_data).decode('utf-8')
            except Exception as e:
                print(f"❌ Error reading image file: {e}")
                return None
            
            # Initialize LangChain ChatOpenAI
            llm = ChatOpenAI(
                model="gpt-4o",
                temperature=0.8,
                max_tokens=50,
                api_key=Config.OPENAI_API_KEY
            )
            
            # Create multimodal message with image and text
            message = HumanMessage(
                content=[
                    {
                        "type": "text",
                        "text": f"""You are an expert art curator. Look at this artwork and create a short and simple description.

Original Description: {description}
Art Category: {art_category}

Generate exactly 8-10 words that feels similar to the image and description.
It should sound like an art catalog caption. Do not repeat the exact wording from the description.
Respond with ONLY the 8-10 word description, nothing else:"""
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/jpeg;base64,{base64_image}"
                        }
                    }
                ]
            )
            
            # Call GPT-4o via LangChain with image
            response = llm.invoke([message])
            seed_description = response.content.strip()
            
            print(f"🤖 GPT-4o generated seed ({len(seed_description.split())} words): {seed_description}")
            
            return seed_description
            
        except Exception as e:
            print(f"❌ Error generating GPT-4o seed: {e}")
            return None
    

    
    def generate_seed(self) -> Optional[tuple[str, str]]:
        """Generate a random seed by selecting a random image and using GPT-4o to create a short description.
        
        Returns:
            Tuple of (seed_description, image_id) or None if failed
        """
        print("🎲 Generating random seed...")
        
        # Step 1: Select random category
        category = self._get_random_category()
        print(f"📂 Selected category: {category.value}")
        
        # Step 2: Get random image from category
        image_path = self._get_random_image_path(category)
        if not image_path:
            print("❌ Failed to get random image path")
            return None
        
        print(f"🖼️  Selected image: {Path(image_path).name}")
        
        # Step 3: Calculate image ID
        image_id = self._calculate_image_id(image_path)
        print(f"🆔 Calculated image ID: {image_id}")
        
        # Step 4: Fetch from Pinecone using VectorDBIngestor
        vector_data = self._fetch_from_pinecone(image_id)
        
        if vector_data and 'metadata' in vector_data:
            # Extract description and category from vector data
            metadata = vector_data['metadata']
            description = metadata.get('description', '')
            art_category = metadata.get('category', category.value)
            
            # Generate short seed using GPT-4o with image input
            seed_description = self._generate_gpt4o_seed(image_path, description, art_category)
            
            if seed_description:
                print("🎉 Successfully generated seed with GPT-4o!")
                return (seed_description, image_id)
            else:
                print("❌ Failed to generate seed with GPT-4o")
                return None
        else:
            print("❌ Failed to generate seed - image not found in Pinecone")
            return None


def main():
    """Main function to test the seed generator."""
    print("🎲 Seed Generator Test")
    print("=" * 40)
    
    # Initialize seed generator
    seed_gen = SeedGenerator()
    
    if not seed_gen.vector_ingestor:
        print("❌ Cannot proceed without VectorDBIngestor connection")
        return
    
    # Generate a single seed
    print("\n🔍 Testing single seed generation:")
    seed_result = seed_gen.generate_seed()
    
    if seed_result:
        seed_description, image_id = seed_result
        print(f"\n📊 Generated Seed: {seed_description}")
        print(f"🆔 Image ID: {image_id}")
    else:
        print("\n❌ Failed to generate seed")

if __name__ == "__main__":
    main() 